## EconomyStatistics Config ##
Settings:
  Messages:
    prefix: "&2[ES] "
    SignPlace: "&aSign Created!"
    SignBreak: "&a"
    Error:
      NoPermission: "&cYou don't have permission!"
  Signs:
    amount: "&2Amount"
    average: "&2Average"
  Database:
    MySQL:
      use: false
      Host: localhost
      Port: 3306
      Database: database
      User: root
      Pass: password
